import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Hero } from './hero';


export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const heroes = [
      { id: 1, name: 'Bulbasaur',image: 'https://img.pokemondb.net/sprites/x-y/normal/bulbasaur.png'  },
      { id: 2, name: 'Ivysaur',image: 'https://img.pokemondb.net/sprites/x-y/normal/ivysaur.png' },
      { id: 3, name: 'Venusaur',image: 'https://img.pokemondb.net/sprites/x-y/normal/venusaur.png' },
      { id: 4, name: 'Charmander',image: 'https://img.pokemondb.net/sprites/x-y/normal/charmander.png' },
      { id: 5, name: 'Charmeleon',image: 'https://img.pokemondb.net/sprites/x-y/normal/charmeleon.png' },
      { id: 6, name: 'Charizard',image: 'https://img.pokemondb.net/sprites/x-y/normal/charizard.png' },
      { id: 7, name: 'Squirle',image: 'https://img.pokemondb.net/sprites/x-y/normal/squirtle.png' },
      { id: 8, name: 'Wartortle',image: 'https://img.pokemondb.net/sprites/x-y/normal/wartortle.png' },
      { id: 9, name: 'Blastoise',image: 'https://img.pokemondb.net/sprites/x-y/normal/blastoise.png' },
      { id: 10, name: 'Caterpie',image: 'https://img.pokemondb.net/sprites/x-y/normal/caterpie.png' },
      { id: 11, name: 'Matapod',image: 'https://img.pokemondb.net/sprites/x-y/normal/metapod.png' },
      { id: 12, name: 'Butterfree',image: 'https://img.pokemondb.net/sprites/x-y/normal/butterfree.png' },
      { id: 13, name: 'Weedle',image: 'https://img.pokemondb.net/sprites/x-y/normal/weedle.png' },
      { id: 14, name: 'Kakuna',image: 'https://img.pokemondb.net/sprites/x-y/normal/kakuna.png' },
      { id: 15, name: 'Beedrill',image: 'https://img.pokemondb.net/sprites/x-y/normal/beedrill.png' },
      { id: 16, name: 'Pidgey',image: 'https://img.pokemondb.net/sprites/x-y/normal/pidgey.png' },
      { id: 17, name: 'Pidgeotto',image: 'https://img.pokemondb.net/sprites/x-y/normal/pidgeotto.png' },
      { id: 18, name: 'Pidgeot',image: 'https://img.pokemondb.net/sprites/x-y/normal/pidgeot.png' },
      { id: 19, name: 'Rattata',image: 'https://img.pokemondb.net/sprites/x-y/normal/rattata.png' },
      { id: 20, name: 'Raticate',image: 'https://img.pokemondb.net/sprites/x-y/normal/raticate.png' },
      { id: 21, name: 'Spearow',image: 'https://img.pokemondb.net/sprites/x-y/normal/spearow.png' },
      { id: 22, name: 'Fearow',image: 'https://img.pokemondb.net/sprites/x-y/normal/fearow.png' },
      { id: 23, name: 'Ekans',image: 'https://img.pokemondb.net/sprites/x-y/normal/ekans.png' },
      { id: 24, name: 'Arbok',image: 'https://img.pokemondb.net/sprites/x-y/normal/arbok.png' },
      { id: 25, name: 'Pikachu',image: 'https://img.pokemondb.net/sprites/x-y/normal/pikachu.png' },
      { id: 26, name: 'Raichu',image: 'https://img.pokemondb.net/sprites/x-y/normal/raichu.png' },
      { id: 27, name: 'Sandshrew',image: 'https://img.pokemondb.net/sprites/x-y/normal/sandshrew.png' },
      { id: 28, name: 'Sandslash',image: 'https://img.pokemondb.net/sprites/x-y/normal/sandslash.png' },
      { id: 29, name: 'Nidoran',image: 'https://img.pokemondb.net/sprites/x-y/normal/nidoran-f.png' },
      { id: 30, name: 'Nidorina',image: 'https://img.pokemondb.net/sprites/x-y/normal/nidorina.png' },
      { id: 31, name: 'Nidoqueen',image: 'https://img.pokemondb.net/sprites/x-y/normal/nidoqueen.png' },
      { id: 32, name: 'Nidoran',image: 'https://img.pokemondb.net/sprites/x-y/normal/nidoran-m.png' },
      { id: 33, name: 'Nidorino',image: 'https://img.pokemondb.net/sprites/x-y/normal/nidorino.png' },
      { id: 34, name: 'Nidoking',image: 'https://img.pokemondb.net/sprites/x-y/normal/nidoking.png' },
      { id: 35, name: 'Clefairy',image: 'https://img.pokemondb.net/sprites/x-y/normal/clefairy.png' },
      { id: 36, name: 'Clefable',image: 'https://img.pokemondb.net/sprites/x-y/normal/clefable.png' },
      { id: 37, name: 'Vulpix',image: 'https://img.pokemondb.net/sprites/x-y/normal/vulpix.png' },
      { id: 38, name: 'Ninetales',image: 'https://img.pokemondb.net/sprites/x-y/normal/ninetales.png' },
      { id: 39, name: 'Jigglypuff',image: 'https://img.pokemondb.net/sprites/x-y/normal/jigglypuff.png' },
      { id: 40, name: 'Wigglytuff',image: 'https://img.pokemondb.net/sprites/x-y/normal/wigglytuff.png' },
      { id: 41, name: 'Zubat',image: 'https://img.pokemondb.net/sprites/x-y/normal/zubat.png' },
      { id: 42, name: 'Golbat',image: 'https://img.pokemondb.net/sprites/x-y/normal/golbat.png' },
      { id: 43, name: 'Oddish',image: 'https://img.pokemondb.net/sprites/x-y/normal/oddish.png' },
      { id: 44, name: 'Gloom',image: 'https://img.pokemondb.net/sprites/x-y/normal/gloom.png' },
      { id: 45, name: 'Vileplume',image: 'https://img.pokemondb.net/sprites/x-y/normal/vileplume.png' },
      { id: 46, name: 'Paras',image: 'https://img.pokemondb.net/sprites/x-y/normal/paras.png' },
      { id: 47, name: 'Parasect',image: 'https://img.pokemondb.net/sprites/x-y/normal/parasect.png' },
      { id: 48, name: 'Venonat',image: 'https://img.pokemondb.net/sprites/x-y/normal/venonat.png' },
      { id: 49, name: 'Venomoth',image: 'https://img.pokemondb.net/sprites/x-y/normal/venomoth.png' },
      { id: 50, name: 'Diglett',image: 'https://img.pokemondb.net/sprites/x-y/normal/diglett.png' },
      { id: 51, name: 'Dugtrio',image: 'https://img.pokemondb.net/sprites/x-y/normal/dugtrio.png' },
      { id: 52, name: 'Meowth',image: 'https://img.pokemondb.net/sprites/x-y/normal/meowth.png' },
      { id: 53, name: 'Persian',image: 'https://img.pokemondb.net/sprites/x-y/normal/persian.png' },
      { id: 54, name: 'Psyduck',image: 'https://img.pokemondb.net/sprites/x-y/normal/psyduck.png' },
      { id: 55, name: 'Golduck',image: 'https://img.pokemondb.net/sprites/x-y/normal/golduck.png' },
      { id: 56, name: 'Mankey',image: 'https://img.pokemondb.net/sprites/x-y/normal/mankey.png' },
      { id: 57, name: 'Primeape',image: 'https://img.pokemondb.net/sprites/x-y/normal/primeape.png' },
      { id: 58, name: 'Growlithe',image: 'https://img.pokemondb.net/sprites/x-y/normal/growlithe.png' },
      { id: 59, name: 'Arcanine',image: 'https://img.pokemondb.net/sprites/x-y/normal/arcanine.png' },
      { id: 60, name: 'Poliwag',image: 'https://img.pokemondb.net/sprites/x-y/normal/poliwag.png' },
      { id: 61, name: 'Poliwhirl',image: 'https://img.pokemondb.net/sprites/x-y/normal/poliwhirl.png' },
      { id: 62, name: 'Poliwrath',image: 'https://img.pokemondb.net/sprites/x-y/normal/poliwrath.png' },
      { id: 63, name: 'Abra',image: 'https://img.pokemondb.net/sprites/x-y/normal/abra.png' },
      { id: 64, name: 'Kadabra',image: 'https://img.pokemondb.net/sprites/x-y/normal/kadabra.png' },
      { id: 65, name: 'Alakazam',image: 'https://img.pokemondb.net/sprites/x-y/normal/alakazam.png' },
      { id: 66, name: 'Machop',image: 'https://img.pokemondb.net/sprites/x-y/normal/machop.png' },
      { id: 67, name: 'Machoke',image: 'https://img.pokemondb.net/sprites/x-y/normal/machoke.png' },
      { id: 68, name: 'Machamp',image: 'https://img.pokemondb.net/sprites/x-y/normal/machamp.png' },
      { id: 69, name: 'Bellsprout',image: 'https://img.pokemondb.net/sprites/x-y/normal/bellsprout.png' },
      { id: 70, name: 'Weepinbell',image: 'https://img.pokemondb.net/sprites/x-y/normal/weepinbell.png' },
      { id: 71, name: 'Victreebel',image: 'https://img.pokemondb.net/sprites/x-y/normal/victreebel.png' },
      { id: 72, name: 'Tentacool',image: 'https://img.pokemondb.net/sprites/x-y/normal/tentacool.png' },
      { id: 73, name: 'Tentacruel',image: 'https://img.pokemondb.net/sprites/x-y/normal/tentacruel.png' },
      { id: 74, name: 'Geodude',image: 'https://img.pokemondb.net/sprites/x-y/normal/geodude.png' },
      { id: 75, name: 'Graveler',image: 'https://img.pokemondb.net/sprites/x-y/normal/graveler.png' },
      { id: 76, name: 'Golem',image: 'https://img.pokemondb.net/sprites/x-y/normal/golem.png' },
      { id: 77, name: 'Ponyta',image: 'https://img.pokemondb.net/sprites/x-y/normal/ponyta.png' },
      { id: 78, name: 'Rapidash',image: 'https://img.pokemondb.net/sprites/x-y/normal/rapidash.png' },
      { id: 79, name: 'Slowpoke',image: 'https://img.pokemondb.net/sprites/x-y/normal/slowpoke.png' },
      { id: 80, name: 'Slowbro',image: 'https://img.pokemondb.net/sprites/x-y/normal/slowbro.png' },
      { id: 81, name: 'Magnemite',image: 'https://img.pokemondb.net/sprites/x-y/normal/magnemite.png' },
      { id: 82, name: 'Magneton',image: 'https://img.pokemondb.net/sprites/x-y/normal/magneton.png' },
      { id: 83, name: 'Farfetch d',image: "https://img.pokemondb.net/sprites/x-y/normal/farfetchd.png" },
      { id: 84, name: 'Doduo',image: 'https://img.pokemondb.net/sprites/x-y/normal/doduo.png' },
      { id: 85, name: 'Dodrio',image: 'https://img.pokemondb.net/sprites/x-y/normal/dodrio.png' },
      { id: 86, name: 'Seel',image: 'https://img.pokemondb.net/sprites/x-y/normal/seel.png' },
      { id: 87, name: 'Dewgong',image: 'https://img.pokemondb.net/sprites/x-y/normal/dewgong.png' },
      { id: 88, name: 'Grimer',image: 'https://img.pokemondb.net/sprites/x-y/normal/grimer.png' },
      { id: 89, name: 'Muk',image: 'https://img.pokemondb.net/sprites/x-y/normal/muk.png' },
      { id: 90, name: 'Shellder',image: 'https://img.pokemondb.net/sprites/x-y/normal/shellder.png' },
      { id: 91, name: 'Cloyster',image: 'https://img.pokemondb.net/sprites/x-y/normal/cloyster.png' },
      { id: 92, name: 'Gastly',image: 'https://img.pokemondb.net/sprites/x-y/normal/gastly.png' },
      { id: 93, name: 'Haunter',image: 'https://img.pokemondb.net/sprites/x-y/normal/haunter.png' },
      { id: 94, name: 'Gengar',image: 'https://img.pokemondb.net/sprites/x-y/normal/gengar.png' },
      { id: 95, name: 'Onix',image: 'https://img.pokemondb.net/sprites/x-y/normal/onix.png' },
      { id: 96, name: 'Drowzee',image: 'https://img.pokemondb.net/sprites/x-y/normal/drowzee.png' },
      { id: 97, name: 'Hypno',image: 'https://img.pokemondb.net/sprites/x-y/normal/hypno.png' },
      { id: 98, name: 'Krabby',image: 'https://img.pokemondb.net/sprites/x-y/normal/krabby.png' },
      { id: 99, name: 'Kingler',image: 'https://img.pokemondb.net/sprites/x-y/normal/kingler.png' },
      { id: 100, name: 'Voltorb',image: 'https://img.pokemondb.net/sprites/x-y/normal/voltorb.png' },
      { id: 101, name: 'Electrode',image: 'https://img.pokemondb.net/sprites/x-y/normal/electrode.png' },
      { id: 102, name: 'Exeggcute',image: 'https://img.pokemondb.net/sprites/x-y/normal/exeggcute.png' },
      { id: 103, name: 'Exeggutor',image: 'https://img.pokemondb.net/sprites/x-y/normal/exeggutor.png' },
      { id: 104, name: 'Cubone',image: 'https://img.pokemondb.net/sprites/x-y/normal/cubone.png' },
      { id: 105, name: 'Marowak',image: 'https://img.pokemondb.net/sprites/x-y/normal/marowak.png' },
      { id: 106, name: 'Hitmonlee',image: 'https://img.pokemondb.net/sprites/x-y/normal/hitmonlee.png' },
      { id: 107, name: 'Hitmonchan',image: 'https://img.pokemondb.net/sprites/x-y/normal/hitmonchan.png' },
      { id: 108, name: 'Lickitung',image: 'https://img.pokemondb.net/sprites/x-y/normal/lickitung.png' },
      { id: 109, name: 'Koffing',image: 'https://img.pokemondb.net/sprites/x-y/normal/koffing.png' },
      { id: 110, name: 'Weezing',image: 'https://img.pokemondb.net/sprites/x-y/normal/weezing.png' },
      { id: 111, name: 'Rhyhorn',image: 'https://img.pokemondb.net/sprites/x-y/normal/rhyhorn.png' },
      { id: 112, name: 'Rhydon',image: 'https://img.pokemondb.net/sprites/x-y/normal/rhydon.png' },
      { id: 113, name: 'Chansey',image: 'https://img.pokemondb.net/sprites/x-y/normal/chansey.png' },
      { id: 114, name: 'Tangela',image: 'https://img.pokemondb.net/sprites/x-y/normal/tangela.png' },
      { id: 115, name: 'Kangaskhan',image: 'https://img.pokemondb.net/sprites/x-y/normal/kangaskhan.png' },
      { id: 116, name: 'Horsea',image: 'https://img.pokemondb.net/sprites/x-y/normal/horsea.png' },
      { id: 117, name: 'Seadra',image: 'https://img.pokemondb.net/sprites/x-y/normal/seadra.png' },
      { id: 118, name: 'Goldeen',image: 'https://img.pokemondb.net/sprites/x-y/normal/goldeen.png' },
      { id: 119, name: 'Seaking',image: 'https://img.pokemondb.net/sprites/x-y/normal/seaking.png' },
      { id: 120, name: 'Staryu',image: 'https://img.pokemondb.net/sprites/x-y/normal/staryu.png' },
      { id: 121, name: 'Starmie',image: 'https://img.pokemondb.net/sprites/x-y/normal/starmie.png' },
      { id: 122, name: 'Mr. Mime',image: 'https://img.pokemondb.net/sprites/x-y/normal/mr-mime.png' },
      { id: 123, name: 'Scyther',image: 'https://img.pokemondb.net/sprites/x-y/normal/scyther.png' },
      { id: 124, name: 'Jynx',image: 'https://img.pokemondb.net/sprites/x-y/normal/jynx.png' },
      { id: 125, name: 'Electabuzz',image: 'https://img.pokemondb.net/sprites/x-y/normal/electabuzz.png' },
      { id: 126, name: 'Magmar',image: 'https://img.pokemondb.net/sprites/x-y/normal/magmar.png' },
      { id: 127, name: 'Pinsir',image: 'https://img.pokemondb.net/sprites/x-y/normal/pinsir.png' },
      { id: 128, name: 'Tauros',image: 'https://img.pokemondb.net/sprites/x-y/normal/tauros.png' },
      { id: 129, name: 'Magikarp',image: 'https://img.pokemondb.net/sprites/x-y/normal/magikarp.png' },
      { id: 130, name: 'Gyarados',image: 'https://img.pokemondb.net/sprites/x-y/normal/gyarados.png' },
      { id: 131, name: 'Lapras',image: 'https://img.pokemondb.net/sprites/x-y/normal/lapras.png' },
      { id: 132, name: 'Ditto',image: 'https://img.pokemondb.net/sprites/x-y/normal/ditto.png' },
      { id: 133, name: 'Eevee',image: 'https://img.pokemondb.net/sprites/x-y/normal/eevee.png' },
      { id: 134, name: 'Vaporeon',image: 'https://img.pokemondb.net/sprites/x-y/normal/vaporeon.png' },
      { id: 135, name: 'Jolteon',image: 'https://img.pokemondb.net/sprites/x-y/normal/jolteon.png' },
      { id: 136, name: 'Flareon',image: 'https://img.pokemondb.net/sprites/x-y/normal/flareon.png' },
      { id: 137, name: 'Porygon',image: 'https://img.pokemondb.net/sprites/x-y/normal/porygon.png' },
      { id: 138, name: 'Omanyte',image: 'https://img.pokemondb.net/sprites/x-y/normal/omanyte.png' },
      { id: 139, name: 'Omastar',image: 'https://img.pokemondb.net/sprites/x-y/normal/omastar.png' },
      { id: 140, name: 'Kabuto',image: 'https://img.pokemondb.net/sprites/x-y/normal/kabuto.png' },
      { id: 141, name: 'Kabutops',image: 'https://img.pokemondb.net/sprites/x-y/normal/kabutops.png' },
      { id: 142, name: 'Aerodactyl',image: 'https://img.pokemondb.net/sprites/x-y/normal/aerodactyl.png' },
      { id: 143, name: 'Snorlax',image: 'https://img.pokemondb.net/sprites/x-y/normal/snorlax.png' },
      { id: 144, name: 'Articuno',image: 'https://img.pokemondb.net/sprites/x-y/normal/articuno.png' },
      { id: 145, name: 'Zapdos',image: 'https://img.pokemondb.net/sprites/x-y/normal/zapdos.png' },
      { id: 146, name: 'Moltres',image: 'https://img.pokemondb.net/sprites/x-y/normal/moltres.png' },
      { id: 147, name: 'Dratini',image: 'https://img.pokemondb.net/sprites/x-y/normal/dratini.png' },
      { id: 148, name: 'Dragonair',image: 'https://img.pokemondb.net/sprites/x-y/normal/dragonair.png' },
      { id: 149, name: 'Dragonite',image: 'https://img.pokemondb.net/sprites/x-y/normal/dragonite.png' },
      { id: 150, name: 'Mewtwo',image: 'https://img.pokemondb.net/sprites/x-y/normal/mewtwo.png' },
      { id: 151, name: 'Mew',image: 'https://img.pokemondb.net/sprites/x-y/normal/mew.png' }
    ];
    return {heroes}
  }

  // Overrides the genId method to ensure that a hero always has an id.
  // If the heroes array is empty,
  // the method below returns the initial number (11).
  // if the heroes array is not empty, the method below returns the highest
  // hero id + 1.
  genId(heroes: Hero[]): number {
    return heroes.length > 0 ? Math.max(...heroes.map(hero => hero.id)) + 1 : 151;
  }
}